# Generated by Django 4.2 on 2023-11-12 18:20

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('position', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('skills', models.TextField(help_text='Comma separated skills', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
