# Generated by Django 4.2 on 2023-11-13 11:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0005_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blocks',
            field=wagtail.fields.StreamField([('name_section', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('name', wagtail.blocks.CharBlock(required=True)), ('position', wagtail.blocks.CharBlock(required=True)), ('company_name', wagtail.blocks.CharBlock(required=True))])), ('about_me', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('content', wagtail.blocks.RichTextBlock(required=True))])), ('work_experience', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('works', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('home.WorkExperience')))]))], blank=True, use_json_field=True, verbose_name='Page body'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('skills', models.TextField(help_text='Comma separated skills', null=True)),
                ('code_link', models.URLField(blank=True, null=True)),
                ('report_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
        ),
    ]
