# Generated by Django 4.2 on 2023-11-13 12:35

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skills', models.TextField(help_text='Comma separated skills', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blocks',
            field=wagtail.fields.StreamField([('name_section', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('name', wagtail.blocks.CharBlock(required=True)), ('position', wagtail.blocks.CharBlock(required=True)), ('company_name', wagtail.blocks.CharBlock(required=True))])), ('about_me', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('content', wagtail.blocks.RichTextBlock(required=True)), ('skill_groups', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('home.SkillGroup')))])), ('work_experience', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('works', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('home.WorkExperience')))])), ('projects', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='ID of this block. Can be used to link the block in header', null=True, required=False)), ('projects', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('home.Project')))]))], blank=True, use_json_field=True, verbose_name='Page body'),
        ),
    ]
